### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by silverpill** [lukeprofits/Monero_Payment_Request_Standard#1]
The format of subscription code will likely evolve over time. New required fields might be added, data types may change, even serialization/compression algorithm can be different.

In anticipation of these changes, I suggest to add a version number to subscription codes. For example:

```
monero-subscription:1:H4sIAGOfSWQC/x2O
```

Version should be increased every time there's a breaking change to the code format. If the version number is omitted, parsers should assume that subscription code has version 0 (currently described in README).

**Comment by lukeprofits** [comment]
Good idea. Will add soon. I have a few other updates to make as well.

**Comment by silverpill** [comment]
Thank you for adding versions. I think this issue can be closed
