### ISSUE TITLE
Use RFC3339 for start_date field

### ISSUE THREAD

**Issue by silverpill** [lukeprofits/Monero_Payment_Request_Standard#2]
1. Currently, `start_date` field doesn't include timezone information. This means subscriber and seller may end up using different moment of time as a starting point.
2. Some applications need more precision (up to a second for streaming payments).

I suggest using [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) timestamp format instead of `%Y-%m-%d`.

Example:

```json
"start_date": "2023-04-26T13:45:33Z",
```

**Comment by lukeprofits** [comment]
I was thinking of going with a Unix Timestamp, but I think you are right. [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) is probably a better format to use.
