### ISSUE TITLE
b64 encoded string off by 1 character in ruby implementation

### ISSUE THREAD

**Issue by snex** [lukeprofits/Monero_Payment_Request_Standard#7]
Hi, I am trying to write a ruby implementation of this, and using your test data I am able to decode and get the correct hash, however when I attempt to encode, my b64 hash seems to be off by 1 character and I am not sure why. I'm not able to tell if this is a bug in ruby's zlib, I am using incorrect params, or something else is going on. Perhaps you can help me identify why this 1 b64 character is off and what it represents?

The string that should come out starts with: "monero-request:1:H4sIAAAAAAAC/y"

The string I am getting is: "monero-request:1:H4sIAAAAAAACAy"

Every character other than the / seems to match. Here is the code I am calling:

```ruby
json_str = request.sort.to_h.to_json.force_encoding('ascii')
compressed_data = StringIO.new
gz = Zlib::GzipWriter.new(compressed_data, 9)
gz.mtime = 0
gz.write(json_str)
gz.close
encoded_str = Base64.encode64(compressed_data.string).gsub("\n", "")
"monero-request:1:#{encoded_str}"
```

**Comment by snex** [comment]
I think I figured it out - the incorrect character seems to correspond to the "Operating System" byte for gzip headers. Yours example has "ff" which corresponds to "unknown" while when I perform gzip on Linux, it naturally gives me "03" for Unix/Linux.

**Comment by lukeprofits** [comment]
@snex glad you figured it out. Can we link to your repo for the ruby implementation?

**Comment by snex** [comment]
Yup, I will ping you as soon as it's up.
